services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: userapi
      MYSQL_USER: userapi
      MYSQL_PASSWORD: userapi
    healthcheck:
      test: mysql -uroot -e 'show databases like "userapi"' && sleep 10 
      timeout: 45s
      interval: 2s
      retries: 60
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      DB_URI: db
      DB_NAME: userapi
      DB_USERNAME: userapi
      DB_PASSWORD: userapi
  
