apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: device-api
      app.kubernetes.io/instance: device-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: device-api
        app.kubernetes.io/instance: device-api
    spec:
      containers:
        - name: device-api
          image: "device-api"
          imagePullPolicy: Always
          ports:
            - name: apiport
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: device-api-configmap
            - secretRef:
                name: device-api-secret
